name: timeseries
channels:
  - conda-forge
  - nodefaults
dependencies:
  - geopandas
  - contextily
  - rasterio
  - jupyter
  - jupyterlab
  - rioxarray
  - xgboost
  - scikit-learn
  - seaborn
  - statsmodels
  - pip:
    - flaml[automl]
    - shap